import { Inter } from "next/font/google";
import "./globals.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";

config.autoAddCss = false;
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
       <div className="flex flex-col min-h-screen max-h-screen">
       <Navbar />
        <main className="flex-grow overflow-y-auto bg-page text-default-text">{children}</main>
        <Footer />
       </div>
      </body>
    </html>
  );
}
